### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Comment by ProPontifex** [comment]
Merge me at your convenience, please. Thank you.

**Comment by ProPontifex** [comment]
Thank you, as always, Belleza.

**Comment by ProPontifex** [comment]
All corrected: please try again to merge.

**Comment by ProPontifex** [comment]
Someone? Please merge this into the main database. Thank you.

**Comment by BellezaEmporium** [comment]
@Dum4G Good to go.

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by ProPontifex** [comment]
Thanks to all!

**Review by Dum4G — APPROVED** [review]

**Review by Alstruit — APPROVED** [review]

**Pull request merged**
