### PR TITLE
added hub premier 1

### PR DESCRIPTION
**Pull request by Zoom-Adr**

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Seems like your spreadsheets program messed up the linings of the CSV file.

**Comment by Zoom-Adr** [comment]
Which program is best to edit the spreadsheet?

Regards,
Syafiq

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by LaneSh4d0w** [comment]
Normally, any spreadsheet reader should work, but it seems that any person that uses Excel over this spreadsheet is having issues with Excel forcing a specific lining over the one being used.

**Comment by Zoom-Adr** [comment]
i will re-do again

**Comment by LaneSh4d0w** [comment]
Please do, if it still does the same, just give me the data to add on the channels.csv file and i'll apply it.

**Comment by Zoom-Adr** [comment]
can u check if this is better?

**Comment by LaneSh4d0w** [comment]
Indeed, this is better. Thanks.

**Comment by Zoom-Adr** [comment]
cheers

**Comment by LaneSh4d0w** [comment]
It seems your fork isn't updated to the latest version. Please update and push the changes you have, it should solve the already added channels.

**Comment by Zoom-Adr** [comment]
updated and push the changes again

**Review by LaneSh4d0w — APPROVED** [review]

**Pull request merged**
