### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Comment by PopeyeTheSai10r** [comment]
```
DDHissar.in: "replaced_by" with value "DD Haryana" fails to match the required pattern
DDJammu.in: "replaced_by" with value "DD Kashir" fails to match the required pattern
```

**Comment by ProPontifex** [comment]
Thanks, Popeye. In Visual Studio, when I try and fix it, I get that damn editing error bug: I'll keep trying.

**Comment by ProPontifex** [comment]
If someone else can correct those errors for me, I'd be grateful. This bug just keeps reappearing in Visual Studio!

**Comment by ProPontifex** [comment]
As I typed, Belleza, I've tried to correct them within Visual Studio but they keep reappearing. If you can do something about that I'd appreciate it.

**Comment by ProPontifex** [comment]
Thanks, as always, Belleza.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Pull request merged**
