### PR TITLE
Add category for Firstlight NZ

### PR DESCRIPTION
**Pull request by applecuckoo**
Firstlight is a Christian channel, so the 'religious' category has been added.

### CODE REVIEW

**Comment by applecuckoo** [comment]
Must've touched this PR while updating, I've put the change back in now so reopening. @freearhey anything I need to change?

**Review by freearhey — CHANGES_REQUESTED** [review]
https://github.com/iptv-org/database/actions/runs/3492184817/jobs/5847227866

> Error: empty lines at the end of file not allowed (data/channels.csv)

**Comment by applecuckoo** [comment]
Hmm, must've broken when I used LibreOffice to edit the file. Investigating.

**Comment by freearhey** [comment]
Try opening the [categories.csv](https://github.com/iptv-org/database/blob/master/data/categories.csv) file in the same way, then just save it and compare to the original. Since the file is much smaller, it should be easier to see what's wrong.

**Comment by applecuckoo** [comment]
Here's what categories.csv looks like in the editor:
categories

**Comment by freearhey** [comment]
Have you tried saving the file through the editor and reopening it?

**Comment by applecuckoo** [comment]
It doesn't seem to be doing anything.
itdidnothing

**Review by freearhey — CHANGES_REQUESTED** [review]
Well, if you open the file in a plain text editor, you will see that there is definitely an extra blank line at the end of the file:

image

Also in each line there are extra commas, which should not be there:

```
,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

In addition, [CRLF](https://askubuntu.com/questions/862204/libre-office-calc-export-to-csv-with-crlf-line-endings) should be used at the end of lines so that the file will display normally on Windows as well.

**Comment by applecuckoo** [comment]
Hmm, I'll try again with VS Code and do another PR

**Comment by applecuckoo** [comment]
Okay, succeded by #1283

**Pull request closed without merging**
