### PR TITLE
Updated data/channels.csv

### PR DESCRIPTION
**Pull request by fraudiay79**
Added ARTKino1.xk, ARTKino2.xk, ARTKino3.xk, ARTDoku1.xk, ARTDoku2.xk, ARTSport1.xk, ARTSport2.xk, ARTSport3.xk, ARTSport4.xk, ARTSport5.xk, KSport1.xk, KSport2.xk, KSport3.xk, KSport4.xk, KSport5.xk, Episode.xk, PrimeTV.xk, SjonvarpSimans.is, SiminnSport.is, SiminnSport2.is, SiminnSport3.is, SiminnSport4.is, Omega.is, Hringbraut.is, Stod2.is, Stod2Fjolskylda.is, Stod2Esport.is, Stod2Sport.is, Stod2Sport2.is, Stod2Sport3.is, Stod2Sport4.is, Stod2Golf.is

### CODE REVIEW

**Comment by LaneSh4d0w** [comment]
Seems like your spreadsheets program messed up with the linings of this CSV file.

**Comment by fraudiay79** [comment]
I have uploaded a fresh version.  Please check if the csv format is correct in this new version.

**Comment by LaneSh4d0w** [comment]
Same issue than the last version.

**Comment by fraudiay79** [comment]
I uploaded a fresh version of the file again.  I believe it was the Icelandic characters that were causing the issue.  I changed it to regular Latin Alphabet.  Let me know if there are still issues

**Comment by LaneSh4d0w** [comment]
Let me see for myself.

**Comment by LaneSh4d0w** [comment]
It's definitely something in regards to the linings. See https://github.com/iptv-org/database/pull/177 for a better look.

**Comment by LaneSh4d0w** [comment]
Format is there 
image

**Pull request closed without merging**
