### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Comment by ProPontifex** [comment]
It is I, AntiPontifex, under a new title (thanks to massive computer troubles)!

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by ProPontifex** [comment]
Please merge: thank you

**Comment by Dum4G** [comment]
@ProPontifex fix today and I'll approve

**Comment by ProPontifex** [comment]
What are the conflicts? I cannot seem to list them all.

**Comment by BellezaEmporium** [comment]
Managed to create a codespace fixing the repo, but I do not have rights to push on the repository.

**Comment by ProPontifex** [comment]
Thanks...hopefully, it'll work!

**Review by BellezaEmporium — APPROVED** [review]

**Comment by BellezaEmporium** [comment]
data/channels.csv
 4233   "CanalPlusPuTuTue.fr" must be derived from the channel name "Canal+ Pu Tu Tue" and the country code "MM"
 4417   "Cartoonito.dk" has an invalid replaced_by "2010-09-30"
 4420   "Cartoonito.no" has an invalid replaced_by "2023-09-04"
 4421   "Cartoonito.se" has an invalid replaced_by "2023-09-04"
 5773   "CMMTVHD.es" has an invalid categories "geberal"
 6212   "CSMystery.cz" has an invalid categories "drama"
 4417   Cartoonito.dk: "replaced_by" with value "2010-09-30" fails to match the required pattern: /^[A-Za-z0-9]+\.[a-z]{2}$/
 4420   Cartoonito.no: "replaced_by" with value "2023-09-04" fails to match the required pattern: /^[A-Za-z0-9]+\.[a-z]{2}$/
 4421   Cartoonito.se: "replaced_by" with value "2023-09-04" fails to match the required pattern: /^[A-Za-z0-9]+\.[a-z]{2}$/

**Review by BellezaEmporium — APPROVED** [review]

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
