### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Review by BellezaEmporium — APPROVED** [review]

**Comment by BellezaEmporium** [comment]
that line was removed : 

ntv.de,n-tv,,,,DE,,,c/DE,deu,,FALSE,,,,https://www.n-tv.de/,https://i.imgur.com/tUSXrVm.png

Was it intentional ?

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Waiting for answer.

**Comment by ProPontifex** [comment]
Yes. It was a duplicate: see errors.

**Review by BellezaEmporium — APPROVED** [review]
Indeed.

**Review by Dum4G — APPROVED** [review]

**Comment by freearhey** [comment]
@ProPontifex As I understand it, the error appeared because you first renamed `ntv.at` to `ntv.de`. Is this done on purpose too?

**Pull request closed without merging**
