### PR TITLE
Updated channels.csv

### PR DESCRIPTION
**Pull request by Dexer125**
Added DTXCzech
Updated some CZ/SK icons to be more consistent

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
The thing is, most of the logos in the database have transparent background (https://iptv-org.github.io/?q=\.cz), so for consistency it's actually better to keep the previous versions.

**Comment by Dexer125** [comment]
> The thing is, most of the logos in the database have transparent background ([https://iptv-org.github.io/?q=\.cz](https://iptv-org.github.io/?q=%5C.cz)), so for consistency it's actually better to keep the previous versions.

Got your point. This change is affecting Czech EPG. I did that because when I load EPG with current icons, it's not consistent. Different sizes, styles, shapes and quality. My plan is to change all CZ/SK Channel logos.

**Comment by freearhey** [comment]
> My plan is to change all CZ/SK Channel logos

And what about the other 29,705 channels?

**Comment by Dexer125** [comment]
> > My plan is to change all CZ/SK Channel logos
> 
> And what about the other 29,705 channels?

As I'm CZ/SK EPG user I don't use other EPGs, same as other CZ/SK people. I'm quite not getting your point. Logos on those 29k.channels are not consistent at all. I just wanted to make CZ/SK consistent. Same thing can be done on there EPGs by other contributors.

**Comment by freearhey** [comment]
Well, If the rest of the logos have to be updated by other community members, I think it's worth asking their opinion first (https://github.com/iptv-org/iptv/discussions) and determine at least the general requirements for these images ("...sizes, styles, shapes and quality").

**Comment by Dexer125** [comment]
> Well, If the rest of the logos have to be updated by other community members, I think it's worth asking their opinion first (https://github.com/iptv-org/iptv/discussions) and determine at least the general requirements for these images ("...sizes, styles, shapes and quality").

Okay, as this would be time consuming for me, can you approve this PR with your change request? Only add back DTX. Thank you

**Comment by freearhey** [comment]
Closed in favor https://github.com/iptv-org/database/commit/a67f02586e926af8b057a83c5266e1344b73ed48

**Pull request closed without merging**
