### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Comment by Dum4G** [comment]
image
Must be /s not /c

**Comment by ProPontifex** [comment]
Thank you for the fixes.

**Comment by ProPontifex** [comment]
Please merge ASAP

**Review by Alstruit — APPROVED** [review]

**Comment by Alstruit** [comment]
In the future, I would highly suggest reducing the number of lines changed to ~500 to avoid conflicts.
@ProPontifex.

**Comment by ProPontifex** [comment]
500 it is

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
