### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by AntiPontifex**
See title

### CODE REVIEW

**Comment by BellezaEmporium** [comment]
data/channels.csv
 936    "AkwaabaMagic.za" must be derived from the channel name "Akwaaba Magic" and the country code "GH"
 937    "AkwaabaMagicAbusua.za" must be derived from the channel name "Akwaaba Magic Abusua" and the country code "GH"

**Comment by AntiPontifex** [comment]
Thank you for the edits: corrected.

**Review by andreisergeevic — APPROVED** [review]

**Review by andreisergeevic — APPROVED** [review]

**Review by andreisergeevic — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]
LGTM.

**Comment by BellezaEmporium** [comment]
Welp xd, broken again.

**Comment by BellezaEmporium** [comment]
1959   "AtacamaNoticias.cl" has an invalid subdivision "Cl-AT"
 1959   AtacamaNoticias.cl: "subdivision" with value "Cl-AT" fails to match the required pattern: /^[A-Z]{2}-[A-Z0-9]{1,3}$/

**Comment by BellezaEmporium** [comment]
For the time being, I'll suggest to not touch this PR until this gets merged.

**Review by BellezaEmporium — DISMISSED** [review]

**Comment by AntiPontifex** [comment]
Fixed: thank you Belleza/Lane

**Review by BellezaEmporium — DISMISSED** [review]

**Review by Alstruit — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
