### PR TITLE
Channel name needs to be same automatically retrieved tvg-id

### PR DESCRIPTION
**Pull request by ExTechOp**
Turns out you can't just willy-nilly change the first column name, it has to match the automatically retrieved tvg-id

### CODE REVIEW

**Comment by freearhey** [comment]
Channel ID must be derived from the channel name "More Star Trek" and the country code "US".

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#data-scheme

**Comment by ExTechOp** [comment]
I have to ask for help here: If you look at https://iptv-org.github.io/iptv/index.m3u you will find the channel `StarTrek2.us` which is this channel, but this does not get propagated to eg. https://iptv-org.github.io/iptv/languages/eng.m3u because there is no matching line in `data/channels.csv` — what is the correct way to correct this discrepancy, where does the `tvg-id` which is used to match the channel originally come from?
On the other hand, [according to Pluto TV publicity materials](https://trekmovie.com/2022/11/01/pluto-tv-lunching-second-star-trek-channel-adding-reruns-of-star-trek-ds9-and-tos/) and [earlier Github discussions](https://github.com/orgs/iptv-org/discussions/989), the channel should properly be called "More Star Trek".

**Comment by freearhey** [comment]
To fix the inconsistency, just edit this line and change the `tvg-id` to the correct one:

https://github.com/iptv-org/iptv/blob/a6daaa946591dafa569804b62aa3ffaf03d8192f/streams/us.m3u#L847

**Comment by ExTechOp** [comment]
I hope I got this right: https://github.com/iptv-org/iptv/pull/15502

**Pull request closed without merging**
