### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Review by freearhey — CHANGES_REQUESTED** [review]
The second-to-last field is used to link to the official websites of the channels, not to link to their social media accounts.

https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#channels

**Comment by ProPontifex** [comment]
I thought it was agreed to use facebook pages when there was no other alternative. Has this changed?

**Comment by freearhey** [comment]
Maybe it's me missing something, could you point me to this discussion?

**Comment by ProPontifex** [comment]
You're not; that standard was established long before I came on the project. Look at the entire database and see how many Facebook page entries there are.

**Comment by freearhey** [comment]
> Look at the entire database and see how many Facebook page entries there are.

77 of 38494 entries

**Comment by ProPontifex** [comment]
For some reason, even though I deleted the Facebook pages in my attempted submit, I cannot submit an update. Feel free to delete or otherwise this request can just sit here indefinitely.

**Review by freearhey — DISMISSED** [review]

**Review by ProPontifex — COMMENTED** [review]
Other than the inclusion of accents, looks good to me.

**Comment by freearhey** [comment]
> For some reason, even though I deleted the Facebook pages in my attempted submit, I cannot submit an update.

To avoid this in the future I can advise you to read these [article](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) before posting your next pull request.

**Review by ProPontifex — COMMENTED** [review]
Thank you

**Review by ProPontifex — COMMENTED** [review]
Ok to me

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Comment by BellezaEmporium** [comment]
Cursed PR lol.

**Review by freearhey — APPROVED** [review]

**Review by BellezaEmporium — APPROVED** [review]

**Pull request merged**
