### PR TITLE
Updated data/channels.csv

### PR DESCRIPTION
**Pull request by Smark223**
Add Sport Klub Croatia and Slovenia channels

### CODE REVIEW

**Comment by Smark223** [comment]
Add Sport Klub Croatia and Slovenia channels

**Comment by freearhey** [comment]
Please read the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description) before posting your next request.

**Comment by Smark223** [comment]
> Please read the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description) before posting your next request.

I have read the contributing guide, was there something wrong with this pull request? I thought I'd fixed the errors I initially submitted. I can't see anything else that doesn't stick to advice in the guide but apologies if this is not correct.

**Comment by freearhey** [comment]
In the list of changes:

> 9,997 additions, 10,226 deletions

https://github.com/iptv-org/database/pull/2073/files

And the main reasons why this might happen are listed in the [Contributing Guide](https://github.com/iptv-org/database/blob/master/CONTRIBUTING.md#how-to-add-a-channel-to-the-database-or-edit-its-description):

> IMPORTANT: Since different programs process CSV files differently before publishing an edited file, please make sure that:
> 
> - no extra columns (commas) were added to the file
> - only [CRLF](https://developer.mozilla.org/en-US/docs/Glossary/CRLF) is used to indicate the end of a line
> - no empty lines at the end of the file

If you can't find any of the above in the file, please try taking a fresh copy of the file and resubmit a Pull Request.

**Comment by Smark223** [comment]
OK, thanks for the explanation. I'll take a fresh copy and resubmit when I get chance, as there are some more additions required.

**Pull request closed without merging**
