### PR TITLE
Update channel.csv

### PR DESCRIPTION
**Pull request by AntiPontifex**
Screw the commits (I don't get why this is coming up), its the changes to channels.csv that I want to contribute. Thanks for your patience.

### CODE REVIEW

**Comment by AntiPontifex** [comment]
I didn't want this to close: my apologies.

**Comment by AntiPontifex** [comment]
If someone could, please push the edited channels.csv to the master. Thanks.

**Review by PopeyeTheSai10r — APPROVED** [review]

**Review by Dum4G — APPROVED** [review]

**Comment by Alstruit** [comment]
Looks like some of the channel ids were removed without good reason.

**Comment by Carlinhos027** [comment]
> Looks like some of the channel ids were removed without good reason.

Which ones?

**Comment by Alstruit** [comment]
> > Looks like some of the channel ids were removed without good reason.
> 
> Which ones?

Dunno git log isn't showing the full picture. Just a thought.

**Comment by AntiPontifex** [comment]
Feel free to fix; I was encountering difficulties with Visual Studio

**Pull request merged**
