### PR TITLE
Update channels.csv to remove USA from channel names and tvg-id

### PR DESCRIPTION
**Pull request by PopeyeTheSai10r**
Proposing this change for consistency across the board.

### CODE REVIEW

**Comment by freearhey** [comment]
The fact is that in many cases "USA" is part of the official name ([ARY Digital USA](https://iptv-org.github.io/?q=ARY%20Digital)).

In those cases where the channel has the same name in different countries I add "US" to the name ([Ariana TV US](https://iptv-org.github.io/?q=Ariana%20TV)), or if the channel originally broadcasts from the US I leave the name as it is ([Discovery Science](https://iptv-org.github.io/?q=Discovery%20Science)).

**Comment by PopeyeTheSai10r** [comment]
Ok. Make sense to keep the channels name the same for those that have US or USA in their official name. I do think we should remove the country suffix for anything that doesn't really have that in the official name.

For example: **American Heroes Channel USA** doesn't need the USA suffix based on their [Wiki page](https://en.wikipedia.org/wiki/American_Heroes_Channel).

**Comment by PopeyeTheSai10r** [comment]
I think we can close this PR for now. I will try to think of a better way to solve this issue.
It is not so much of a problem for USA channels but it is a lot worse for other countries' channels.

**Comment by freearhey** [comment]
>  I do think we should remove the country suffix for anything that doesn't really have that in the official name.

I would love to do this, but unfortunately the official name often does not take into account other versions of the same channel. For example, the Wikipedia article does not mention the Canadian version of American Heroes Channel, even though we have a separate guide for it: https://iptv-org.github.io/?q=American%20Heroes%20Channel

As for the American Heroes Channel USA, I've already fixed its name (https://github.com/iptv-org/database/commit/b3929df4e25b1e44c8bf5da92ec51671c367fb97).

**Pull request closed without merging**
