### PR TITLE
Update channels

### PR DESCRIPTION
**Pull request by davidclaeysquinones**
I've changed the icon for ViaplayTv to a png as previously requested and added another additional channel.

### CODE REVIEW

**Comment by shikenie** [comment]
is there a way to add south korea tvn channel? tia.

**Comment by davidclaeysquinones** [comment]
Of course there is, but I'm trying to limit the scope of my PR in order to get it approved.
I'm having some issues getting them approved so I kinda don't want to take the risk.

**Comment by davidclaeysquinones** [comment]
The reason I didn't filed an issue is that I wanted to help out.
It seemed more reasonable to submit an individual change rather than ask for it.
I'm sorry if my actions had the opposite effect.
I've made some changes to my PR and run them through the validate script.
It seems like now there are no issues.

**Review by Dum4G — DISMISSED** [review]

**Review by BellezaEmporium — APPROVED** [review]
LGTM.

**Review by BellezaEmporium — CHANGES_REQUESTED** [review]
Erh, wait, not LGTM. ViaplayTV is not supposed to be mixed with the SBS channels, it should be a bit below. Have you checked if there wasn't a duplicate ?

**Comment by davidclaeysquinones** [comment]
The SBS channel was replaced by Viaplay. 
This [link](https://www.viaplaygroup.com/news/news-releases/viaplay-group-and-talpa-network-enter-linear-tv-partnership-netherlands-2217663) proves what i'm saying.

**Comment by davidclaeysquinones** [comment]
I filled in the replaced by columna but not the closet column. I'll make those changes and put Viaplay by alphabetical order.

**Review by BellezaEmporium — APPROVED** [review]

**Comment by BellezaEmporium** [comment]
LGTM. Thank you.

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
