### PR TITLE
Update channels.csv

### PR DESCRIPTION
**Pull request by ProPontifex**
See title

### CODE REVIEW

**Comment by ProPontifex** [comment]
Please try and merge: Belleza, when you have the time, could you please correct? Thank you.

**Review by Alstruit — COMMENTED** [review]
Are you attempting to switch the countries from where the broadcast originates to where it is received?

**Comment by ProPontifex** [comment]
If I change the country of origin for a channel, it always defaults to where it originates. If I made a mistake, feel free to correct :)

**Comment by ProPontifex** [comment]
(Belleza?) Would some please be kind enough to correct and merge these changes. Thank you in advance.

**Comment by BellezaEmporium** [comment]
I have been summoned it seems. I'm checking the merge conflicts tomorrow.

**Comment by ProPontifex** [comment]
Thank you, sir

**Comment by BellezaEmporium** [comment]
Resolved.

 9248   "GalvestonCountyTV.us" has the wrong broadcast_area "c/US-TX"
 9406   "GFNTV.us" has an invalid categories "entrertainment"
 9464   "Glendale11AZ.us" has the wrong broadcast_area "c/US-AZ"
 8830   Food52.us: "owners[0]" with value "Food52, Inc" fails to match the required pattern: /^[^",]+$/
 9248   GalvestonCountyTV.us: "broadcast_area[0]" with value "c/US-TX" fails to match the required pattern: /^(s\/[A-Z]{2}-[A-Z0-9]{1,3}|c\/[A-Z]{2}|r\/[A-Z0-9]{2,7})$/
 9248   GalvestonCountyTV.us: "broadcast_area" does not contain 1 required value(s)
 9464   Glendale11AZ.us: "broadcast_area[0]" with value "c/US-AZ" fails to match the required pattern: /^(s\/[A-Z]{2}-[A-Z0-9]{1,3}|c\/[A-Z]{2}|r\/[A-Z0-9]{2,7})$/
 9464   Glendale11AZ.us: "broadcast_area" does not contain 1 required value(s)

**Comment by ProPontifex** [comment]
Corrections made: thank you

**Comment by BellezaEmporium** [comment]
9741   GreenChannel.jp: "owners[0]" with value "Satellite Broadcasting Foundation for Horseracing, Agriculture, Forestry and Fisheries" fails to match the required pattern: /^[^",]+$/
 9742   GreenChannel2.jp: "owners[0]" with value "Satellite Broadcasting Foundation for Horseracing, Agriculture, Forestry and Fisheries" fails to match the required pattern: /^[^",]+$/

These should be wrapped in "".

**Comment by ProPontifex** [comment]
Thanks Belleza: I just took the commas out *shrug*

**Review by BellezaEmporium — APPROVED** [review]
OK, all good now. No touching until PR gets merged.

**Comment by ProPontifex** [comment]
Copy that: thank you

**Review by Dum4G — APPROVED** [review]

**Pull request merged**
